<?php

namespace ContainerSZPXUSy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KYEXwhHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KYEXwhH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KYEXwhH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dateHelper' => ['services', 'App\\Service\\DateHelper', 'getDateHelperService', true],
        ], [
            'dateHelper' => 'App\\Service\\DateHelper',
        ]);
    }
}
